### ISSUE TITLE
this code not work on python3.5

### ISSUE THREAD

**Issue by starapp** [FriendCode/gittle#95] opened 2017-05-17 09:59 UTC
i don't know how to do,so i chang str to bytes samewhere and bytes to str somewhere ,finally it works

**Comment by jelmer** [comment] 2017-08-19 01:50
See https://github.com/FriendCode/gittle/issues/63

**Comment by AaronO** [comment] 2017-08-19 13:57
Closing as duplicate of #63

**Closed as completed by AaronO** 2017-08-19 13:57 UTC
